packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/@core/forward/*
  - packages/@core/*
  - packages/effects/*
  - packages/business/*
  - apps/*
  - scripts/*
  - docs
  - playground
catalog:
  '@changesets/changelog-github': ^0.5.0
  '@changesets/cli': ^2.27.9
  '@changesets/git': ^3.0.1
  '@commitlint/cli': ^19.5.0
  '@commitlint/config-conventional': ^19.5.0
  '@types/node': ^22.8.2
  '@types/eslint': ^9.6.1
  '@typescript-eslint/eslint-plugin': ^8.12.2
  '@typescript-eslint/parser': ^8.12.2
  '@eslint/js': ^9.13.0
  '@manypkg/get-packages': ^2.2.2
  '@vitejs/plugin-vue': ^5.1.4
  '@vitejs/plugin-vue-jsx': ^4.0.1
  '@stylistic/stylelint-plugin': ^3.1.1
  chalk: ^5.3.0
  cac: ^6.7.14
  circular-dependency-scanner: ^2.3.0
  cspell: ^8.15.4
  consola: ^3.2.3
  cross-env: ^7.0.3
  cz-git: ^1.10.1
  czg: ^1.10.1
  commitlint-plugin-function-rules: ^4.0.0
  dayjs: ^1.11.13
  depcheck: ^1.4.7
  dotenv: ^16.4.5
  eslint: ^9.13.0
  eslint-config-turbo: ^2.2.3
  eslint-plugin-command: ^0.2.6
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.3.1
  eslint-plugin-jsdoc: ^50.4.3
  eslint-plugin-jsonc: ^2.16.0
  eslint-plugin-n: ^17.11.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^3.9.1
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-regexp: ^2.6.0
  eslint-plugin-unicorn: ^56.0.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^9.30.0
  execa: ^9.5.1
  find-up: ^7.0.0
  get-port: ^7.1.0
  globals: ^15.11.0
  husky: ^9.1.6
  is-ci: ^3.0.1
  jsonc-eslint-parser: ^2.4.0
  lint-staged: ^15.2.10
  ora: ^8.1.0
  publint: ^0.2.12
  pkg-types: ^1.2.1
  postcss: ^8.4.47
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.7.0
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.0.8
  postcss-scss: ^4.0.9
  prettier: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.8
  rimraf: ^6.0.1
  rollup: ^4.24.2
  rollup-plugin-visualizer: ^5.12.0
  stylelint: ^16.10.0
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.5.0
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.2
  stylelint-scss: ^6.8.1
  tailwindcss: ^3.4.14
  turbo: ^2.2.3
  typescript: ^5.6.3
  unbuild: ^2.0.0
  vite: ^5.4.10
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: 4.2.1
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-lib-inject-css: ^2.1.1
  vite-plugin-pwa: ^0.20.5
  vite-plugin-vue-devtools: ^7.5.4
  vitepress: ^1.4.1
  vitepress-plugin-group-icons: ^1.3.0
  vitest: ^2.1.4
  vue: ^3.5.12
  vue-eslint-parser: ^9.4.3
  vue-router: ^4.4.5
  vue-tsc: ^2.1.8
